// react-project/src/pages/register.tsx
import React, {FC, useState} from "react";
import { useNavigate } from 'react-router-dom';
import useUserId from "../hooks/user-id.hook.ts";

export const Register: FC = () => {
    const navigate = useNavigate();
    const [username, setUsername] = useState('');
    const [repeatPassword, setRepeatPassword] = useState('');
    const [password, setPassword] = useState('');
    const [error, setError] = useState('');
    const normalInputClasses = "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
    const errorInputClasses = "bg-red-50 border border-red-500 text-red-900 text-sm rounded-lg focus:ring-red-500 focus:border-red-500 block w-full p-2.5"
    const normalTextClasses = "block mb-2 text-sm font-medium text-gray-900"
    const errorTextClasses = "block mb-2 text-sm font-medium text-red-700"
    const { setUserId } = useUserId()

    const handleSubmit = async (event: React.FormEvent) => {
        event.preventDefault();

        if (password !== repeatPassword) {
            setError('Passwords do not match')
            return;
        }

        try {
            const response = await fetch('http://localhost:3000/users/register', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({ username, password })
            });

            if (response.ok) {
                const data = await response.json();
                setUserId(data.id);
                navigate('/todo');
            } else {
                setError('Failed to register')
            }
        } catch (error) {
            setError('Failed to register')
        }
    };

    return (
        <form className="max-w-sm w-full mx-auto" onSubmit={handleSubmit}>
            <div className="mb-5">
                <label htmlFor="username" className={error ? errorTextClasses : normalTextClasses}>
                    Your username</label>
                <input type="text" id="username" value={username}
                       className={error ? errorInputClasses : normalInputClasses}
                       placeholder="JohnDoe"
                       onChange={(e) => setUsername(e.target.value)}
                       required/>
            </div>
            <div className="mb-5">
                <label htmlFor="password" className={error ? errorTextClasses : normalTextClasses}>
                    Your password</label>
                <input type="password" id="password" value={password}
                       className={error ? errorInputClasses : normalInputClasses}
                       onChange={(e) => setPassword(e.target.value)}
                       required/>
            </div>
            <div className="mb-5">
                <label htmlFor="repeatPassword" className={error ? errorTextClasses : normalTextClasses}>
                    Repeat password</label>
                <input type="password" id="repeatPassword" value={repeatPassword}
                       className={error ? errorInputClasses : normalInputClasses}
                       onChange={(e) => setRepeatPassword(e.target.value)}
                       required/>
            </div>
            {error && (
                <p className="text-red-700 text-sm font-medium mb-5">{error}</p>
            )}
            <div className="mb-5">
                <a href="/" className="text-blue-700 hover:underline">Login</a>
            </div>
            <button type="submit"
                    className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center">Register
            </button>
        </form>
);
};

// svelte-project/src/routes/register/+page.svelte
<script lang="ts">
    import { goto } from '$app/navigation';
    import { userId } from "../../store/userid.ts";

    let username = '';
    let password = '';
    let repeatPassword = '';
    let error = '';
    const normalInputClasses = "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
    const errorInputClasses = "bg-red-50 border border-red-500 text-red-900 text-sm rounded-lg focus:ring-red-500 focus:border-red-500 block w-full p-2.5"
    const normalTextClasses = "block mb-2 text-sm font-medium text-gray-900"
    const errorTextClasses = "block mb-2 text-sm font-medium text-red-700"

    const handleSubmit = async (event: Event) => {
        event.preventDefault();

        if (password !== repeatPassword) {
            error = 'Passwords do not match';
            return;
        }

        try {
            const response = await fetch('http://localhost:3000/users/register', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({ username, password })
            });

            if (response.ok) {
                const data = await response.json();
                $userId = data.id;
                await goto('/todo');
            } else {
                error = 'Failed to register';
            }
        } catch (error) {
            error = 'Failed to register';
        }
    };
</script>

<div>
    <form class="max-w-sm w-full mx-auto" on:submit={handleSubmit}>
        <div class="mb-5">
            <label for="username" class={error ? errorTextClasses : normalTextClasses}>
                Your username</label>
            <input type="text" id="username"
                   class={error ? errorInputClasses : normalInputClasses}
                   placeholder="JohnDoe"
                   bind:value={username}
                   required/>
        </div>
        <div class="mb-5">
            <label for="password" class={error ? errorTextClasses : normalTextClasses}>
                Your password</label>
            <input type="password" id="password"
                   class={error ? errorInputClasses : normalInputClasses}
                   bind:value={password}
                   required/>
        </div>
        <div class="mb-5">
            <label for="repeatPassword" class={error ? errorTextClasses : normalTextClasses}>
                Repeat password</label>
            <input type="password" id="repeatPassword"
                   class={error ? errorInputClasses : normalInputClasses}
                   bind:value={repeatPassword}
                   required/>
        </div>
        {#if error}
            <p class="text-red-700 text-sm font-medium mb-5">{error}</p>
        {/if}
        <div class="mb-5">
            <a href="/" class="text-blue-700 hover:underline">Login</a>
        </div>
        <button type="submit"
                class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center">Register
        </button>
    </form>
</div>
